spring.application.name=spring-app

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CarmanDB;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Ninguna26#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjMxM2Y5Nzk1YTAzNjQ0YWQ4NGQ2NDk4NWExNTQ4YjAzIiwiaCI6Im11cm11cjY0In0=

